project:
  type: website
  output-dir: docs

website:
  title: "STA 9750 Submission Material"
  description: "Course Projects for STA 9750 at Baruch College"
  site-url: "https://miggonzalz.github.io/STA9750-2026-SPRING/"
  navbar:
    background: primary  # Changed to 'primary' for a more distinct header
    search: true         # Helpful for navigating large data projects
    left:
      - text: "Home"
        href: index.qmd
      - text: "MP01"
        href: mp01.qmd
      - text: "MP02"        
        href: mp02.qmd
      - text: "MP03"        
        href: mp03.qmd
      - text: "MP04"        
        href: mp04.qmd     
      - text: "Individual Report"        
        href: individual_report.qmd
      - text: "Summary Report"        
        href: summary_report.qmd
execute:
  warning: false
  message: false

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-fold: true
    page-layout: full
    css: styles.css

editor:
  mode: source